name: Android Build (Optimized for Low Memory)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Signal Debug
    runs-on: ubuntu-latest

    env:
      # Limit Gradle JVM memory
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.jvm.options=-Xmx1g"

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Set up Android SDK (default install, no deprecated args)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # Accept SDK licenses
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      # Limit Kotlin compiler memory in gradle.properties
      - name: Configure Gradle properties
        run: |
          echo "org.gradle.jvmargs=-Xmx3g" >> gradle.properties
          echo "kotlin.daemon.jvmargs=-Xmx1024m" >> gradle.properties

      # Build only the debug variant (lighter than PlayStagingDebug)
      - name: Build Signal Debug APK
        run: ./gradlew assembleDebug --no-daemon --console=plain --max-workers=2

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signal-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
