name: Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Gradle build (assembleDebug)
        run: |
          ./gradlew --no-daemon --stacktrace \
            clean :app:assembleDebug -x test

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            app/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/*/app-*.apk
          if-no-files-found: error
